### ISSUE TITLE
How are 'future states' sampled?

### ISSUE THREAD

**Issue by tombewley** [facebookresearch/controllable_agent#4]
https://github.com/facebookresearch/controllable_agent/blob/5a9950b07f1edcb4bddd04f5819379541793d975/url_benchmark/in_memory_replay_buffer.py#L157-L161

Hi - thanks for making your implementation public! I'm reading through the code alongside your NeurIPS/ICLR papers and I'd just like to clarify something about how 'future states' ($s'$ in the papers) should be sampled during updates.

In the papers, $s'$ is said to be sampled from $\rho$ independently from $(s_t,a_t)$, but in the attached snippet of code you appear to be sampling $s'$ from **the future of the same episode** as $s_t$ (using geometric discounting). This seems to be inconsistent to me. I understand why you might intuitively want to sample in this way (so that $s'$ is more likely to be 'reachable' from $s_t$) but as far as I'm aware that's not what's assumed in your theory and proofs.

Am I misunderstanding something here? Thanks in advance!

---

*P.S. from my understanding, both `DiscreteFBAgent` and `FBDDPGAgent` currently use the replay buffer implementation from `in_memory_replay_buffer.py` rather than `replay_buffer.py` (the import of the latter is commented out). Is this the version used in the paper results?*

**Comment by ahmed-touati** [comment]
Hi Tom, thanks for you interest. 

```future_obs``` in the replay buffer are only used for the contrastive learning method to define the positive examples.
for FB method, $s'$ and $s_t$ are sampled i.i.d from $\rho$ like in theory. In practise, we can use the same mini-batch $(s_i, a_i)$ of size n, compute all the pairwise inner-product $M_{i,j} = F(s_i, a_i)^\top B(s_j)$ for all $i, j$ and then we obtain an unbiased estimate of $E_{(s, a) \sim \rho, s' \sim \rho}[F(s, a)^\top B(s')]$ by averaging the off-diagonal terms of $M$ i.e $\frac{1}{n(n-1)} \sum_{i, j, i \neq j}  F(s_i, a_i)^\top B(s_j)$ since $s_i, s_j$ are independent for $i \neq j$. 
I hope it is helpful.

PS: we use ```in_memory_replay_buffer.py``` for the experimental version of the paper.

**Comment by tombewley** [comment]
Hi Ahmed, I appreciate you responding so quickly - this makes perfect sense, thanks!
